

model_name: led_abs
vocab_size: 50265
freeze_bert: False
d_model: 768
num_heads: 8
dropout: 0.1 
norm_first: True
num_encoder_blocks: 2
num_decoder_blocks: 2
layer_norm_eps: 1.0e-6
d_ff: 2048
max_position_embeddings: 4000

dec_layers: 4
dec_hidden_size: 768
dec_heads: 8
dec_ff_size: 2048
dec_dropout: 0.2

# bert_model: bert-base-cased
bert_model: allenai/led-base-16384
type_doc_size: 2

# bert_config:
#     vocab_size: 28997
#     hidden_size: 768
#     pad_token_id: 0
#     hidden_dropout_prob: 0.1
#     type_vocab_size: 2
#     type_doc_size: 2
#     max_position_embeddings: 5000
#     position_embedding_type: absolute