

model_name: basic_ext
freeze_bert: False
d_model: 768
num_heads: 8
dropout: 0.1 
norm_first: False
num_encoder_blocks: 2
layer_norm_eps: 1.0e-6
d_ff: 2048

bert_config:
    vocab_size: 28997
    hidden_size: 768
    pad_token_id: 0
    hidden_dropout_prob: 0.1
    type_vocab_size: 2
    type_doc_size: 2
    max_position_embeddings: 5000
    position_embedding_type: absolute