task: abs
mode: test

bert_data_path: ./abs_bert_data_shards/multi_news_abs.bert_data
model_path: /content/gdrive/MyDrive/__projects/thesis/bertabs/saved_models_p2/
result_path: /content/gdrive/MyDrive/__projects/thesis/bertabs/saved_models_p2/part_2
temp_dir: ./temp

model_config_path: model_config.yaml
checkpoint: null


train_from: null
test_from: /content/gdrive/MyDrive/__projects/thesis/bertabs/saved_models_p2/model_step_25000.pt
log_file: ./logs/model_log

block_trigram: True
report_rouge: True


# general
batch_size: 500
test_batch_size: 2500

max_pos: 512
max_position_embeddings: 800
use_interval: True

# hyperparameters
## param init 
param_init: 0
param_init_glorot: True
## optimizer
optim: adam
lr: 2.0e-3
beta1: 0.9
beta2: 0.999
warmup_steps: 8000
warmup_steps_bert: 8000
warmup_step_dec: 8000
max_grad_norm: 0

# train phase
save_checkpoint_steps: 1000
accum_count: 5
report_every: 100
train_steps: 20000
recall_eval: True
## trainer 
label_smoothing: 0.1
generator_shard_size: 32
alpha: 0.6 
beam_size: 5
min_length: 150
max_length: 800
max_tgt_len: 1024 
ext_predict_nsents: 20

# gpu
visible_gpus: '0'
gpu_ranks: '0'
world_size: 1
seed: 666

test_all: true
load_from_extractive: ""
sep_optim: True

test_start_from: -1